/**
 * Auto-generated redirects for archived Oasis-era blog/docs.
 * Regenerated by: node scripts/generate-archived-content-redirects.js
 * Do not hand-edit.
 */
module.exports = {
  "blogRedirects": [
    {
      "source": "/blog/10-browser-security-best-practices-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/16-billion-password-leak-crisis-2025",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/16-billion-passwords-leaked-enterprise-browsers-shield-organization-2025",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/20-questions-approve-ai-powered-browser-work-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/2026-browser-paradox-lower-latency-higher-fan-noise",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/5g-networks-india-vs-us-comparison",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/7-ai-browser-features-youll-actually-use-summaries-commands-organization-security-oasis-playbook-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/advanced-thermal-management-materials-ar-glasses-2025",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/agentic-ai-browser-autonomous-task-execution-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/agentic-ai-browser-breakthrough-2025",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/agentic-browsers-101-hands-free-web-automation-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/agentic-browsers-competitive-research-without-losing-plot-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/ai-assistants-browsers-real-vs-hype-commands-matter-oasis-field-guide-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/ai-breaking-web-search-changes-browsing-2026-oasis-take",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/ai-browser-assistants-silent-data-leakers-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/ai-browser-fragmentation-cross-platform-challenges-2025",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/ai-browser-privacy-crisis-2025-smart-safer-alternatives-analysis",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/ai-browser-privacy-logging-forensics-compliance-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/ai-browser-revolution-security-privacy-crisis-2025",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/ai-browser-search-disruption-2025-zero-click-economy-crisis",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/ai-browser-vs-traditional-browser-difference-2025",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/ai-browser-wars-2025-comet-genspark-dia-comparison",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/ai-browsers-chrome-alternatives-power-users-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/ai-browsers-privacy-dilemma-2025",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/ai-browsers-ready-enterprise-security-compliance-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/ai-browsers-replacing-traditional-search-everyday-tasks-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/ai-browsers-shadow-soc-front-end-security-decisions-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/ai-chat-browsers-vs-ai-execution-gap-oasis-explanation-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/ai-powered-browsing-vs-chatgpt-why-browser-layer-matters-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/ai-powered-reading-summaries-highlights-smart-collections-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/amazon-north-carolina-ai-powerhouse",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/anthropic-ai-transforming-work-developers-skill-erosion-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/antivirus-browser-extensions-security-challenges-2025",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/antivirus-chrome-extension-dilemma-2025",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/arc-browser-vs-chrome-vs-oasis-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/arc-vs-sigmaos-best-project-browser-oasis-copies-changes-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/autonomous-browser-governance-who-governs-it-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/battery-life-showdown-2026-browser-laptop-drain-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/battery-vs-benchmarks-edge-chrome-efficient-paper-drain-laptop-road-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/best-ai-browser-2026-tested-what-actually-helps-you-work-oasis-included-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/best-ai-browser-extensions-2026-disappointing-reasons",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/best-ai-browsers-2026-tested-real-workflows",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/best-browser-low-end-laptops-2026-benchmark-vs-efficiency",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/best-chrome-alternatives-2026-brave-firefox-ai-browsers",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/best-enterprise-browsers-2025",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/best-enterprise-browsers-2026-buyers-guide-what-actually-matters-oasis-buyer-guide",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/best-extensions-for-ai-browsers-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/brave-leo-vs-opera-aria-workflow-comparison-tabs-summaries-actions-oasis-review-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/brave-tor-oasis-privacy-forensic-usability-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/brave-vs-safari-vs-oasis-challenges-2025",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/browser-ai-privacy-what-gets-logged-what-leaks-oasis-privacy-lens-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/browser-based-dlp-explained-copy-paste-downloads-screenshots-printing-oasis-security-lens-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/browser-definition-challenges-2025",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/browser-downloads-challenges-limitations-2025",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/browser-evolution-crisis-2025-ai-disruption-legacy-vs-innovation",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/browser-fingerprinting-dark-web-unique-private-setup-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/browser-history-deletion-challenges-2025",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/browser-key-challenges-limitations-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/browser-native-dlp-copy-paste-screenshot-controls-2025",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/browser-new-security-perimeter-breaches-start-tabs-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/browser-security-crisis-2025-ai-browsers-vulnerabilities-challenges",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/browser-security-crisis-2025-chrome-safari-oasis-comparison",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/browser-security-threats-finance-oasis",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/browser-settings-challenges-trends-2025",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/browser-speed-tests-2026-lab-winners-real-world-losers",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/browser-speed-vs-security-remote-work-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/browser-speed-wars-2026-fastest-depends-what-doing",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/browser-summarization-research-notes-next-steps-oasis-workflow-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/building-more-than-server-revamping-kahana-discord-creative-community-2025",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/built-in-browser-ai-vs-extensions-speed-reliability-privacy-oasis-breakdown-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/byod-zero-trust-rise-enterprise-browser",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/cartier-data-breach-analysis-2025",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/case-study-remote-team-oasis-enterprise-browser-reduce-context-switching-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/challenges-of-free-virtual-browsers-2025",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/choosing-right-secure-enterprise-browser-saas-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/chrome-ai-vs-edge-ai-2026-real-differences-oasis-playbook-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/chrome-apps-challenges-2025",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/chrome-browser-challenges-limitations-2025",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/chrome-browser-challenges-trends-2025",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/chrome-default-browser-challenges-2025",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/chrome-download-challenges-trends-2025",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/chrome-edge-brave-vivaldi-vs-oasis-same-engine-different-speed-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/chrome-enterprise-mac-challenges-2025",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/chrome-enterprise-x64-windows-10-challenges-2025",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/chrome-extensions-vs-native-ai-features-oasis-what-you-can-replace-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/chrome-for-mac-everything-you-need-to-know-2025",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/chrome-gemini-vs-ai-extensions-whats-better-real-work-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/chrome-incognito-challenges-2025",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/chrome-installation-challenges-2025",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/chrome-installer-challenges-misconceptions-2025",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/chrome-internet-browser-challenges-limitations-2025",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/chrome-policy-removal-challenges-2025",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/chrome-settings-challenges-2025",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/chrome-tab-groups-best-practices-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/chrome-update-challenges-2025",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/chrome-vs-firefox-vs-oasis-enterprise-2025",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/chrome-vs-safari-vs-oasis-browser-security-privacy-challenges-2025",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/chrome-vs-safari-vs-oasis-enterprise-browser-security-analysis-2025",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/chromebook-browser-challenges-2025",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/chromium-arm-laptops-performance-efficiency-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/chromium-browser-challenges-2025",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/chromium-browsers-2026-benchmarks-ram-real-world",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/chromium-enterprise-browser-reduces-saas-compatibility-headaches-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/chromium-enterprise-browsers-safest-bet-saas-organizations-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/comet-ai-browser-security-risks-safety-analysis-vulnerability-report-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/compliance-friendly-browsing-enterprise-browsers-soc2-hipaa-gdpr-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/customizing-enterprise-browser-settings-departmental-needs-2025",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/dark-web-browsers-challenges-trends-2025",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/dark-web-browsers-tor-i2p-freenet-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/dark-web-vs-privacy-browsers-tor-brave-firefox-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/dark-web-vs-private-browsers-tor-overkill-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/data-leakage-browsers-copy-paste-downloads-shadow-it-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/data-leaks-in-2025-prevention-strategies-for-enterprises",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/data-vulnerability-in-2025-emerging-threats-and-enterprise-defense-strategies",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/default-browser-challenges-2025",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/designing-browser-level-zero-trust-for-saas-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/detecting-eme-cdm-support-wild-developers-mistakes-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/drm-chrome-edge-safari-firefox-enterprise-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/drm-telemetry-device-ids-shadow-tracking-browser-vendor-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/drm-user-privacy-innovation-browsers-locked-down-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/drm-vs-enterprise-dlp-browser-data-protection-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/drm-zero-trust-enterprise-browser-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/edge-search-challenges-2025",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/energy-browser-security-patchwork-2025",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/energy-utilities-browser-blind-spot",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/energy-utilities-digital-opportunity-2025",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/energy-utilities-enterprise-browser-security",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/energy-utilities-remote-access-challenges-2025",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/enterprise-access-browser-windows-10-research-2025",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/enterprise-architecture-challenges-ai-browsers-architects-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/enterprise-browser-adoption-challenges-2025",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/enterprise-browser-adoption-trends-why-now-whats-changing-oasis-market-take-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/enterprise-browser-dlp-replace-traditional-model-2025",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/enterprise-browser-economics-2026-funding-pricing-roi",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/enterprise-browser-features-checklist-sso-dlp-clipboard-downloads-audit-logs-oasis-guide-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/enterprise-browser-market-leaders-winning-why-2026-oasis-market-take",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/enterprise-browser-productivity-challenges-2025",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/enterprise-browser-security-performance-sso-dlp-extensions-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/enterprise-browser-showdown-oasis-vs-island-a-2025-comparison",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/enterprise-browser-vs-consumer-browser-policies-isolation-oasis-buyer-lens-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/enterprise-browser-vs-remote-browser-isolation-rbi-saas-data-leaks-oasis-security-lens-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/enterprise-browser-vs-vdi-vpn-modern-access-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/enterprise-browsers-new-perimeter-saas-first-companies-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/enterprise-browsers-remote-work-compliance-2025",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/enterprise-browsers-security-and-trends-2025",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/enterprise-browsing-vs-vdi-when-each-wins-why-users-hate-one-oasis-buyer-lens-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/enterprise-vs-consumer-browsers-productivity-management-modern-workplace-part-2",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/enterprise-vs-consumer-browsers-securing-modern-workforce-part-1",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/escape-tab-overload-oasis-beats-chrome-multitaskers-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/evaluating-impact-browser-extensions-enterprise-security-2025",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/extension-bloat-clean-chromium-install-faster-than-daily-driver-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/family-safe-browsing-2026-filters-tracker-blocking-kid-friendly-browsers",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/fast-but-heavy-chromium-browsers-trade-speed-ram-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/fastest-browser-gaming-streaming-research-task-specific-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/fastest-browser-illusion-extensions-ram-inp-benchmarks-misleading-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/fastest-web-browser-2026-benchmarks-caveats-real-world-problems",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/fastest-web-browsers-2025",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/finance-browser-management-blind-spot",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/finance-browser-security-patchwork-2025",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/finance-enterprise-browser-security",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/finance-remote-access-dilemma-2025",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/firefox-enterprise-challenges-2025",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/for-creators-agentic-browsers-research-scripts-draft-content-stay-organized-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/for-founders-why-founders-moving-workflow-into-agentic-browser-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/for-remote-teams-building-calm-remote-work-stack-agentic-browser-enterprise-browser-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/for-security-teams-why-security-team-should-care-which-browser-company-uses-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/from-chaos-to-calm-oasis-focus-browsing-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/future-ai-browsers-chat-workflow-automation-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/future-proofing-enterprise-browsers-emerging-web-technologies-2025",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/gemini-chrome-how-it-works-enable-limitations-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/generative-ai-reducing-search-volume-seo-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/genspark-autopilot-mode-breaks-copy-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/get-ai-to-control-your-browser-execution-gap-oasis-demo-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/google-chrome-data-collection-advertising-practices-2025",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/google-chrome-enterprise-2025-security-and-productivity",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/google-chrome-enterprise-download-challenges-2025",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/google-chrome-enterprise-installer-challenges-2025",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/google-chrome-enterprise-msi-research-2025",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/government-browser-management-crisis",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/government-digital-opportunity-2025",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/government-enterprise-browser-security",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/government-public-sector-remote-access-challenges-2025",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/healthcare-browser-management-crisis",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/healthcare-browser-security-patchwork-2025",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/healthcare-cisos-ai-security-scaling-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/healthcare-digital-dilemma-2025",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/healthcare-enterprise-browser-security",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/healthcare-remote-access-trap-2025",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/hidden-costs-contractor-laptops-enterprise-browsers-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/hidden-performance-tax-browser-extensions-ai-agents-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/high-price-finance-digital-opportunity-2025",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/how-ai-changes-browser-security-new-attack-surfaces-defenses-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/how-ai-sidebars-extensions-quietly-kill-fastest-browser-claims-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/how-browser-drm-works-eme-cdm-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/how-enterprise-browsers-power-zero-trust-architecture-2025",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/how-to-check-browser-leaking-identifiers-tor-vpn-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/how-to-enable-tab-groups-chrome-run-like-system-oasis-workflow-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/how-to-group-tabs-in-chrome-oasis-ai-commands-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/how-to-protect-saas-data-without-device-control-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/how-to-sync-bookmarks-across-browsers-organize-tab-groups-oasis-workflow-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/identifying-best-browser-challenges-2025",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/ie-mode-end-of-life-legacy-browser-breaking-point-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/incognito-mode-privacy-myths-technical-limitations-2025",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/incognito-mode-vs-real-privacy-what-chrome-doesnt-protect-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/incognito-tab-challenges-2025",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/incognito-window-challenges-2025",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/ingram-micro-ransomware-attack-critical-supply-chain-vulnerability-2025",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/inside-chromium-enterprise-browser-isolation-policy-dlp-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/inside-drm-session-eme-license-server-cdm-flow-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/integrating-ai-tools-enterprise-browsers-opportunities-challenges-2025",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/interaction-to-next-paint-inp-metric-explains-why-browser-feels-laggy-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/internet-browser-challenges-trends-2025",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/internet-browsers-challenges-2025",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/internet-explorer-aftermath-lingering-problems-2025",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/is-chromium-still-best-foundation-fast-browser-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/is-comet-ai-browser-good-beyond-demo-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/island-browser-challenges-2025",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/island-enterprise-browser-revolutionizing-corporate-security",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/island-talon-layerx-enterprise-browser-buyer-guide-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/islands-250m-series-e-ciso-it-leaders-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/jetstream-to-reality-synthetic-benchmarks-dont-measure-browser-speed-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/latency-over-load-time-new-browser-performance-war-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/legacy-browser-breaking-point-enterprise-security-stack-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/logii-browser-challenges-research-2025",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/mainline-health-systems-data-breach-investigation-2025",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/managed-browser-policy-enforcement-what-it-can-cannot-control-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/managed-browser-policy-enforcement-what-it-can-cannot-control-oasis-it-lens-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/manufacturing-browser-blind-spot",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/manufacturing-cybersecurity-opportunities-2025",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/manufacturing-enterprise-browser-security",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/manufacturing-remote-access-dilemma-2025",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/manufacturing-security-patchwork-2025",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/micro-jank-macro-pain-tiny-ui-delays-make-fast-browsers-feel-slow-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/microsoft-edge-browser-challenges-trends-2025",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/microsoft-edge-browser-limitations-misconceptions-2025",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/microsoft-edge-browser-ongoing-issues-vulnerabilities-2025",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/microsoft-edge-enterprise-download-guide-2025",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/microsoft-edge-for-business-deploy-secure-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/microsoft-edge-installer-everything-you-need-to-know-2025",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/migrate-chrome-to-oasis-without-losing-data-workflow",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/modernizing-ie-dependent-apps-activex-vbscript-modern-web-stacks-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/multi-tab-browser-performance-resource-strain-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/netskope-dlp-limitations-unmanaged-endpoints-oasis-2025",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/network-dlp-to-session-dlp-browser-external-users-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/no-admin-rights-managed-browser-locked-down-devices-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/oasis-browser-thinks-in-projects-not-tabs",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/okta-limitations-browser-security-oasis-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/okta-netskope-third-party-access-enterprise-browser-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/okta-saas-iam-challenges-oasis-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/okta-saas-session-security-oasis-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/okta-vpn-enterprise-browser-contractor-onboarding-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/on-device-vs-cloud-ai-browser-security-privacy-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/online-browser-testing-challenges-trends-2025",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/online-security-extensions-challenges-2025",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/openai-browser-ai-evaluation-honest-testing-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/openai-cerebras-10-billion-deal-risks-challenges-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/opera-browser-2025",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/opera-browser-2026-ai-web3-future-browsing-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/opera-browser-ai-features-aria-what-it-does-what-it-misses-oasis-review-march-29-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/opera-chromebook-2026-strengths-weaknesses",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/opera-for-chromebook-2025",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/opera-vs-vivaldi-vs-oasis-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/perplexity-comet-vs-chatgpt-atlas-vs-oasis-2025-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/perplexity-comet-vs-chrome-vs-oasis-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/perplexity-comet-vs-dia-vs-oasis-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/phishing-promptshing-ai-browser-attacks-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/power-users-leaving-chrome-privacy-ai-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/practical-checklist-enterprise-app-browser-drm-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/privacy-vs-convenience-ai-browser-era-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/private-browser-challenges-2025",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/private-browser-misconceptions-2025",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/private-browsers-issues-misconceptions-2025",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/private-browsing-vs-dark-web-incognito-does-not-equal-invisible-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/prompt-injection-browser-hijack-ai-assistant-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/prompt-injection-llm01-risks-challenges-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/protecting-sensitive-data",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/proxy-browser-download-challenges-2025",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/public-sector-browser-security-patchwork-2025",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/recent-research-on-free-adblocker-browsers-2025",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/recent-research-on-free-web-browser-trends-2025",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/recent-research-trends-browser-monitoring-challenges-limitations",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/recent-research-trends-private-browsing-incognito-mode-challenges-limitations",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/rise-enterprise-browsers-corporate-security-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/rise-of-ai-first-browsers-address-bar-chat-box-2025",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/rise-of-ai-first-browsers-address-bar-chat-box-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/risk-over-centralizing-security-enterprise-browser-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/saas-data-exfiltration-browser-contractor-risks-oasis-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/safest-ways-explore-dark-web-2026-operational-security-101",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/saving-tab-groups-in-microsoft-edge-how-it-works-better-alternatives-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/secure-browser-challenges-2025",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/secure-dns-disabled-by-organization-managed-browsers-oasis-it-lens-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/secure-enterprise-browser-1000-employees-rollout-checklist-oasis-rollout-playbook-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/secure-research-workflows-vpn-private-browser-ai-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/secure-web-browsers-2025",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/secure-web-gateway-vs-enterprise-browser-what-to-deploy-first-why-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/securing-energy-utilities-browser-security",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/securing-healthcare-frontline-oasis-browser",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/securing-manufacturing-enterprise-browsers-oasis",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/securing-modern-workspace-dns-rebinding-protection-enterprise-browsing-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/securing-public-sector-browser-security-oasis",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/securing-short-term-consultants-without-mdm-browser-only-strategy-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/shadow-it-browser-saas-insider-risk-contractors-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/shipping-laptops-vdi-enterprise-browser-contractors-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/single-threaded-bottlenecks-modern-web-apps-break-fast-chromium-browsers-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/soc-dark-web-monitoring-employee-privacy-laws-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/speedometer-scores-vs-cpu-browser-benchmarks-lying-power-users-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/ssl-inspection-enterprise-browser-without-breaking-saas-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/sso-browser-okta-concepts-session-controls-common-failure-modes-oasis-troubleshooting-lens-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/step-by-step-retiring-internet-explorer-ie-mode-safely-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/stop-shipping-laptops-managed-chromium-browser-contractor-access-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/supported-browser-challenges-2025",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/supported-browsers-2026-enterprise-compatibility-policy",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/swg-sse-enterprise-browser-extending-netskope-controls-any-device-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/tab-groups-collapse-bugs-fixes-workarounds-oasis",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/tab-overload-cognitive-load-productivity-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/tab-switch-test-better-way-judge-browser-speed-than-benchmark-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/talon-acquisition-turning-point-enterprise-browser-security",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/talonwork-browser-challenges-2025",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/technical-reality-anonymity-dark-web-fingerprinting-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/the-ai-browser-security-crisis-2025-perplexity-chrome-oasis-comparison",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/the-browser-security-trilemma-2025-perplexity-chrome-oasis-vulnerability-analysis",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/the-comeback-play-how-legacy-brands-use-nostalgia-to-win-the-future-2025",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/the-future-of-ergonomic-work-improving-health-2025",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/the-future-of-ergonomic-work-key-players-2025",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/the-future-of-ergonomic-work-next-steps-2025",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/the-future-of-ergonomic-work-problem-analysis-2025",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/the-future-of-ergonomic-work-solution-technology-2025",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/the-hidden-data-leakage-problem-in-saas-apps-and-how-enterprise-browsers-solve-it",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/the-most-secure-web-browsers-in-2025",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/the-rise-of-enterprise-browsers-transforming-corporate-security-in-2025",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/the-truth-about-private-browsing-what-enterprise-users-need-to-know",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/third-party-contractor-access-employee-hr-data-risks-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/true-cost-plugin-stack-measuring-browser-speed-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/ubs-chain-iq-cybersecurity-breach",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/victorias-secret-cybersecurity-breach-2025",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/virtual-machine-browsers-trends-2025",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/vpn-tor-privacy-browsers-layered-security-overlapping-myths-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/vpns-secure-browsers-ai-modern-privacy-stack-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/weaponizing-ie-mode-jquery-4-breaking-point-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/web-browser-challenges-2025",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/web-browser-challenges-trends-2025",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/web-browsers-challenges-limitations-2025",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/what-is-enterprise-browser-2025",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/when-startup-boost-backfires-background-processes-hidden-cpu-spikes-chromium-browsers-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/which-browser-uses-least-ram-chrome-edge-brave-vivaldi-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/why-25-percent-enterprises-moving-managed-browsers-2028-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/why-enterprise-browsers-needed-overcoming-browser-gaps-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/why-oasis-trumps-dia-comet-enterprise-browser-superiority-2025",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/why-you-shouldnt-use-chrome-at-work",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/why-your-browser-benchmarks-great-ac-power-crawls-battery-saver-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/why-your-browser-scores-fast-but-scrolls-like-molasses-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/widevine-playready-fairplay-enterprise-security-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/windows-11-chrome-troubled-partnership-2025",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/windows-browser-challenges-2025",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/windows-vs-macos-vs-linux-fastest-browser-by-os-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/work-browser-slower-personal-enterprise-performance-gap-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/your-tech-compass-oasis-browser-review-87-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/zero-forensic-traces-myth-dark-web-browsers-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/zero-trust-browsing-explained-browser-control-plane-2026",
      "destination": "/blog",
      "permanent": true
    },
    {
      "source": "/blog/zero-trust-explained-browser-first-line-of-defense-2026",
      "destination": "/blog",
      "permanent": true
    }
  ],
  "docsRedirects": [
    {
      "source": "/docs/active-tool-indicator",
      "destination": "/docs",
      "permanent": true
    },
    {
      "source": "/docs/assistant-and-cloud-data",
      "destination": "/docs",
      "permanent": true
    },
    {
      "source": "/docs/assistant-themes",
      "destination": "/docs",
      "permanent": true
    },
    {
      "source": "/docs/autofill",
      "destination": "/docs",
      "permanent": true
    },
    {
      "source": "/docs/busy-streaming-state",
      "destination": "/docs",
      "permanent": true
    },
    {
      "source": "/docs/chat-history-indexeddb",
      "destination": "/docs",
      "permanent": true
    },
    {
      "source": "/docs/chat-history-popover",
      "destination": "/docs",
      "permanent": true
    },
    {
      "source": "/docs/chat-timeline",
      "destination": "/docs",
      "permanent": true
    },
    {
      "source": "/docs/composer-and-follow-ups",
      "destination": "/docs",
      "permanent": true
    },
    {
      "source": "/docs/composer-microphone",
      "destination": "/docs",
      "permanent": true
    },
    {
      "source": "/docs/connection-settings",
      "destination": "/docs",
      "permanent": true
    },
    {
      "source": "/docs/connection-upgrades",
      "destination": "/docs",
      "permanent": true
    },
    {
      "source": "/docs/containers",
      "destination": "/docs",
      "permanent": true
    },
    {
      "source": "/docs/crash-report",
      "destination": "/docs",
      "permanent": true
    },
    {
      "source": "/docs/daily-token-usage-bar",
      "destination": "/docs",
      "permanent": true
    },
    {
      "source": "/docs/deceptive-content-protection",
      "destination": "/docs",
      "permanent": true
    },
    {
      "source": "/docs/default-protection",
      "destination": "/docs",
      "permanent": true
    },
    {
      "source": "/docs/delete-my-account",
      "destination": "/docs",
      "permanent": true
    },
    {
      "source": "/docs/destructive-action-confirmations",
      "destination": "/docs",
      "permanent": true
    },
    {
      "source": "/docs/dns-over-https",
      "destination": "/docs",
      "permanent": true
    },
    {
      "source": "/docs/docked-sidebar-vs-floating-overlay",
      "destination": "/docs",
      "permanent": true
    },
    {
      "source": "/docs/drm-content",
      "destination": "/docs",
      "permanent": true
    },
    {
      "source": "/docs/earn-chip-hints",
      "destination": "/docs",
      "permanent": true
    },
    {
      "source": "/docs/echo-guard",
      "destination": "/docs",
      "permanent": true
    },
    {
      "source": "/docs/enhanced-tracking-protection",
      "destination": "/docs",
      "permanent": true
    },
    {
      "source": "/docs/extension-recommendations",
      "destination": "/docs",
      "permanent": true
    },
    {
      "source": "/docs/external-feedback-links",
      "destination": "/docs",
      "permanent": true
    },
    {
      "source": "/docs/feature-recommendations",
      "destination": "/docs",
      "permanent": true
    },
    {
      "source": "/docs/firefox-relay-integration",
      "destination": "/docs",
      "permanent": true
    },
    {
      "source": "/docs/first-run-data-policy-url",
      "destination": "/docs",
      "permanent": true
    },
    {
      "source": "/docs/global-privacy-control",
      "destination": "/docs",
      "permanent": true
    },
    {
      "source": "/docs/google-trending-search-firefox-address-bar",
      "destination": "/docs",
      "permanent": true
    },
    {
      "source": "/docs/guest-vs-signed-in",
      "destination": "/docs",
      "permanent": true
    },
    {
      "source": "/docs/header-help-menu",
      "destination": "/docs",
      "permanent": true
    },
    {
      "source": "/docs/hidden-firefox-account-toolbar-button",
      "destination": "/docs",
      "permanent": true
    },
    {
      "source": "/docs/https-only-mode",
      "destination": "/docs",
      "permanent": true
    },
    {
      "source": "/docs/import-from-other-browsers",
      "destination": "/docs",
      "permanent": true
    },
    {
      "source": "/docs/import-opt-out",
      "destination": "/docs",
      "permanent": true
    },
    {
      "source": "/docs/improve-oasis-suggest",
      "destination": "/docs",
      "permanent": true
    },
    {
      "source": "/docs/insert-capabilities-overview",
      "destination": "/docs",
      "permanent": true
    },
    {
      "source": "/docs/kahana-supabase-sign-in",
      "destination": "/docs",
      "permanent": true
    },
    {
      "source": "/docs/lockwise-alerts",
      "destination": "/docs",
      "permanent": true
    },
    {
      "source": "/docs/long-session-memory-railroad",
      "destination": "/docs",
      "permanent": true
    },
    {
      "source": "/docs/media-keyboard-control",
      "destination": "/docs",
      "permanent": true
    },
    {
      "source": "/docs/multi-step-agent-loop",
      "destination": "/docs",
      "permanent": true
    },
    {
      "source": "/docs/new-tab-and-assistant-landing",
      "destination": "/docs",
      "permanent": true
    },
    {
      "source": "/docs/notifications",
      "destination": "/docs",
      "permanent": true
    },
    {
      "source": "/docs/oasis-assistant-feature-callout",
      "destination": "/docs",
      "permanent": true
    },
    {
      "source": "/docs/oasis-assistant-in-the-sidebar",
      "destination": "/docs",
      "permanent": true
    },
    {
      "source": "/docs/oasis-branding",
      "destination": "/docs",
      "permanent": true
    },
    {
      "source": "/docs/oasis-suggest",
      "destination": "/docs",
      "permanent": true
    },
    {
      "source": "/docs/oasis-toolbar-pill",
      "destination": "/docs",
      "permanent": true
    },
    {
      "source": "/docs/oasis-turn-off-secure-dns",
      "destination": "/docs",
      "permanent": true
    },
    {
      "source": "/docs/oasis-welcome-not-firefox-about-welcome",
      "destination": "/docs",
      "permanent": true
    },
    {
      "source": "/docs/on-device-embeddings",
      "destination": "/docs",
      "permanent": true
    },
    {
      "source": "/docs/onboarding-checklist-assistant-panel",
      "destination": "/docs",
      "permanent": true
    },
    {
      "source": "/docs/payment-methods",
      "destination": "/docs",
      "permanent": true
    },
    {
      "source": "/docs/performance",
      "destination": "/docs",
      "permanent": true
    },
    {
      "source": "/docs/personalized-extension-recommendations",
      "destination": "/docs",
      "permanent": true
    },
    {
      "source": "/docs/picture-in-picture",
      "destination": "/docs",
      "permanent": true
    },
    {
      "source": "/docs/plain-english-browser-control",
      "destination": "/docs",
      "permanent": true
    },
    {
      "source": "/docs/post-sign-in-assistant",
      "destination": "/docs",
      "permanent": true
    },
    {
      "source": "/docs/primary-password",
      "destination": "/docs",
      "permanent": true
    },
    {
      "source": "/docs/profile-management",
      "destination": "/docs",
      "permanent": true
    },
    {
      "source": "/docs/quick-actions",
      "destination": "/docs",
      "permanent": true
    },
    {
      "source": "/docs/reduced-motion",
      "destination": "/docs",
      "permanent": true
    },
    {
      "source": "/docs/resource-usage",
      "destination": "/docs",
      "permanent": true
    },
    {
      "source": "/docs/router-and-usage-metadata",
      "destination": "/docs",
      "permanent": true
    },
    {
      "source": "/docs/router-assist-usage",
      "destination": "/docs",
      "permanent": true
    },
    {
      "source": "/docs/split-view-for-assistant-actions",
      "destination": "/docs",
      "permanent": true
    },
    {
      "source": "/docs/spoken-vs-chat-replies-orb",
      "destination": "/docs",
      "permanent": true
    },
    {
      "source": "/docs/sponsor-privacy",
      "destination": "/docs",
      "permanent": true
    },
    {
      "source": "/docs/storage-permissions",
      "destination": "/docs",
      "permanent": true
    },
    {
      "source": "/docs/subscription-refresh",
      "destination": "/docs",
      "permanent": true
    },
    {
      "source": "/docs/technical-and-interaction-data",
      "destination": "/docs",
      "permanent": true
    },
    {
      "source": "/docs/third-party-certificates",
      "destination": "/docs",
      "permanent": true
    },
    {
      "source": "/docs/thumbs-and-structured-feedback",
      "destination": "/docs",
      "permanent": true
    },
    {
      "source": "/docs/total-cookie-protection",
      "destination": "/docs",
      "permanent": true
    },
    {
      "source": "/docs/tracking-protection-settings",
      "destination": "/docs",
      "permanent": true
    },
    {
      "source": "/docs/training",
      "destination": "/docs",
      "permanent": true
    },
    {
      "source": "/docs/training-gallery-and-milestones",
      "destination": "/docs",
      "permanent": true
    },
    {
      "source": "/docs/trending-search-suggestions",
      "destination": "/docs",
      "permanent": true
    },
    {
      "source": "/docs/usage-ping-settings",
      "destination": "/docs",
      "permanent": true
    },
    {
      "source": "/docs/voice-and-sign-in",
      "destination": "/docs",
      "permanent": true
    },
    {
      "source": "/docs/voice-orb-hands-free",
      "destination": "/docs",
      "permanent": true
    },
    {
      "source": "/docs/weather-customization",
      "destination": "/docs",
      "permanent": true
    },
    {
      "source": "/docs/welcome-back-after-sign-out",
      "destination": "/docs",
      "permanent": true
    },
    {
      "source": "/docs/what-can-oasis-do-faq",
      "destination": "/docs",
      "permanent": true
    }
  ]
};
