/**
 * Auto-generated redirects for archived Oasis marketing pages.
 * Regenerated by: node scripts/generate-archived-oasis-page-redirects.js
 * Kept live: /oasis-pricing, /installations, /oasis-auth, surveys.
 */
module.exports = {
  "pageRedirects": [
    {
      "source": "/buyers-guide",
      "destination": "/",
      "permanent": true
    },
    {
      "source": "/data-leakage-consortium",
      "destination": "/",
      "permanent": true
    },
    {
      "source": "/enterprise-buyer-guide",
      "destination": "/",
      "permanent": true
    },
    {
      "source": "/features/oasis-amplifier",
      "destination": "/features",
      "permanent": true
    },
    {
      "source": "/features/oasis-assistant",
      "destination": "/features",
      "permanent": true
    },
    {
      "source": "/features/oasis-confirmations",
      "destination": "/features",
      "permanent": true
    },
    {
      "source": "/features/oasis-enterprise-external-access",
      "destination": "/features",
      "permanent": true
    },
    {
      "source": "/features/oasis-enterprise-faster-paths",
      "destination": "/features",
      "permanent": true
    },
    {
      "source": "/features/oasis-enterprise-governance",
      "destination": "/features",
      "permanent": true
    },
    {
      "source": "/features/oasis-enterprise-identity-dlp",
      "destination": "/features",
      "permanent": true
    },
    {
      "source": "/features/oasis-import",
      "destination": "/features",
      "permanent": true
    },
    {
      "source": "/features/oasis-onboarding",
      "destination": "/features",
      "permanent": true
    },
    {
      "source": "/features/oasis-voice",
      "destination": "/features",
      "permanent": true
    },
    {
      "source": "/features/user-analytics",
      "destination": "/features",
      "permanent": true
    },
    {
      "source": "/markets",
      "destination": "/",
      "permanent": true
    },
    {
      "source": "/markets/all",
      "destination": "/",
      "permanent": true
    },
    {
      "source": "/markets/education",
      "destination": "/",
      "permanent": true
    },
    {
      "source": "/markets/energy-utilities",
      "destination": "/",
      "permanent": true
    },
    {
      "source": "/markets/finance",
      "destination": "/",
      "permanent": true
    },
    {
      "source": "/markets/government",
      "destination": "/",
      "permanent": true
    },
    {
      "source": "/markets/healthcare",
      "destination": "/",
      "permanent": true
    },
    {
      "source": "/markets/hospitality",
      "destination": "/",
      "permanent": true
    },
    {
      "source": "/markets/manufacturing",
      "destination": "/",
      "permanent": true
    },
    {
      "source": "/markets/professional",
      "destination": "/",
      "permanent": true
    },
    {
      "source": "/markets/retail",
      "destination": "/",
      "permanent": true
    },
    {
      "source": "/markets/technology",
      "destination": "/",
      "permanent": true
    },
    {
      "source": "/oasis-augmented-reality",
      "destination": "/",
      "permanent": true
    },
    {
      "source": "/oasis-beta-program",
      "destination": "/oasis-pricing",
      "permanent": true
    },
    {
      "source": "/oasis-mobile",
      "destination": "/oasis-pricing",
      "permanent": true
    },
    {
      "source": "/oasis-waitlist",
      "destination": "/oasis-pricing",
      "permanent": true
    },
    {
      "source": "/products",
      "destination": "/oasis-pricing",
      "permanent": true
    },
    {
      "source": "/products/oasis-browser",
      "destination": "/oasis-pricing",
      "permanent": true
    },
    {
      "source": "/products/oasis-enterprise-browser",
      "destination": "/oasis-pricing",
      "permanent": true
    },
    {
      "source": "/products/web-application",
      "destination": "/oasis-pricing",
      "permanent": true
    },
    {
      "source": "/sales",
      "destination": "/",
      "permanent": true
    },
    {
      "source": "/schedule-demo",
      "destination": "/",
      "permanent": true
    },
    {
      "source": "/solutions",
      "destination": "/",
      "permanent": true
    },
    {
      "source": "/solutions/external-workforce",
      "destination": "/",
      "permanent": true
    },
    {
      "source": "/solutions/government",
      "destination": "/",
      "permanent": true
    },
    {
      "source": "/solutions/healthcare",
      "destination": "/",
      "permanent": true
    },
    {
      "source": "/solutions/merger-integration",
      "destination": "/",
      "permanent": true
    },
    {
      "source": "/solutions/privileged-user-management",
      "destination": "/",
      "permanent": true
    },
    {
      "source": "/solutions/remote-workforce",
      "destination": "/",
      "permanent": true
    },
    {
      "source": "/solutions/saas-and-web-apps",
      "destination": "/",
      "permanent": true
    },
    {
      "source": "/solutions/secure-browsing",
      "destination": "/",
      "permanent": true
    },
    {
      "source": "/solutions/vdi-reduction",
      "destination": "/",
      "permanent": true
    },
    {
      "source": "/solutions/workplace-enablement",
      "destination": "/",
      "permanent": true
    },
    {
      "source": "/solutions/zero-trust-security",
      "destination": "/",
      "permanent": true
    },
    {
      "source": "/subscribe-to-insights",
      "destination": "/",
      "permanent": true
    },
    {
      "source": "/thankyou-demo",
      "destination": "/",
      "permanent": true
    },
    {
      "source": "/use-cases",
      "destination": "/",
      "permanent": true
    },
    {
      "source": "/use-cases/job-search",
      "destination": "/",
      "permanent": true
    },
    {
      "source": "/white-paper-future-of-ergonomic-work",
      "destination": "/",
      "permanent": true
    }
  ]
};
